progetto Venederdi 19 07/Models/Anagrafica.cs
namespace progetto_Venederdi_19_07
{
    public class Anagrafica
    {

        public int IdAnagrafica { get; set; }

        public string Cognome { get; set; }

        public string Nome { get; set; }

        public string Cod_Fisc { get; set; }

        public string Indirizzo { get; set; }

        public string Città { get; set; }

        public string Cap { get; set; }

    }
}

progetto Venederdi 19 07/Models/ErrorViewModel.cs
namespace progetto_Venederdi_19_07.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

progetto Venederdi 19 07/Models/Trasgressore.cs
namespace progetto_Venederdi_19_07
{
    public class Trasgressore
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public DateTime DataNascita { get; set; }
    }
}

progetto Venederdi 19 07/Models/Verbale.cs
namespace progetto_Venederdi_19_07
{
    public class Verbale
    {

        public int IdVerbale { get; set; }

        public int IdUtente { get; set; }

        public int IdViolazione { get; set; }

        public DateTime DataViolazione { get; set; }

        public string IndirizzoViolazione { get; set; }

        public string Nominativo_Agente { get; set; }

        public string DataTrascrizioneVerbale { get; set; }

        public decimal Importo { get; set; }

        public int DecurtamentoPunti { get; set; }

    }
}

progetto Venederdi 19 07/Models/Violazione.cs
namespace progetto_Venederdi_19_07
{
    public class Violazione
    {
        public int IdViolazione { get; set; }
        public string Descrizione { get; set; }

    }

}

progetto Venederdi 19 07/ViewModels/UtentiViewModel.cs
namespace progetto_Venederdi_19_07.ViewModels
{
    public class UtentiViewModel
    {

        public int IdAnagrafica { get; set; }

        public string Cognome { get; set; }

        public string Nome { get; set; }

        public string Cod_Fisc { get; set; }

        public string Indirizzo { get; set; }

        public string Città { get; set; }

        public string Cap { get; set; }

    }
}

progetto Venederdi 19 07/ViewModels/VerbaleViewModel.cs
namespace progetto_Venederdi_19_07.ViewModels
{
    public class VerbaleViewModel
    {
       public string Nome { get; set; }

        public string Cognome { get; set; }

        public string Descrizione { get; set; }

        public int TotVerbali { get; set; }

        public int IdVerbale { get; set; }

        public int IdUtente { get; set; }

        public int IdViolazione { get; set; }

        public DateTime DataViolazione { get; set; }

        public string IndirizzoViolazione { get; set; }

        public string Nominativo_Agente { get; set; }

        public DateTime DataTrascrizioneVerbale { get; set; }

        public decimal Importo { get; set; }

        public int DecurtamentoPunti { get; set; }
    }
}

progetto Venederdi 19 07/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using progetto_Venederdi_19_07.Models;
using System.Diagnostics;

namespace progetto_Venederdi_19_07.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

progetto Venederdi 19 07/Controllers/UtentiController.cs
using Microsoft.AspNetCore.Mvc;
using progetto_Venederdi_19_07.ViewModels;
using progetto_Venederdi_19_07.Services;

namespace progetto_Venederdi_19_07.Controllers
{
    public class UtentiController : Controller
    {
        public readonly UtentiService _utentiService;

        public UtentiController(UtentiService utentiService)
        {
            _utentiService = utentiService;
        }

        public IActionResult Index()
        {

            List<UtentiViewModel> utenti = _utentiService.NuovoUtente();

            return View(utenti);
        }

        public IActionResult NuovoUtente()
        {   
            ViewBag.Utenti = _utentiService.NuovoUtente();

            return View();
        }

        [HttpPost]

        public IActionResult NuovoUtente(UtentiViewModel utente)
        {
            _utentiService.NuovoUtente(utente);

            return RedirectToAction("Index");
        }

    }
}

progetto Venederdi 19 07/Controllers/VerbaleController.cs
using Microsoft.AspNetCore.Mvc;
using progetto_Venederdi_19_07.Services;
using progetto_Venederdi_19_07.ViewModels;
using System.Collections.Generic;

namespace progetto_Venederdi_19_07.Controllers
{
    public class VerbaleController : Controller
    {
        public readonly UtentiService _utentiService;

        public readonly VerbaleService _verbaleService;

        public VerbaleController(VerbaleService verbaleService , UtentiService utentiService)
        {
            _utentiService = utentiService;
            _verbaleService = verbaleService;
        }

        public IActionResult Index()
        {

            List<VerbaleViewModel> verbali = _verbaleService.GetVerbali();
            
            return View(verbali);


            
        }

        public IActionResult NuovoVerbale()
        {

            ViewBag.Utenti = _utentiService.NuovoUtente();
            ViewBag.Violazioni = _verbaleService.TutteLeViolazioni();
            


            return View();
        }

        [HttpPost]
        public IActionResult NuovoVerbale(VerbaleViewModel verb)
        {  
            _verbaleService.NuovoVerbale(verb);

            

            return RedirectToAction("Index");
        }
        public IActionResult TotVerbali ()
    { 
        List<VerbaleViewModel> verbali = _verbaleService.TotVerbTrasgressore();
        return View(verbali);
        
    }

        public IActionResult TotPunti ()
        {
            List<VerbaleViewModel> verbali = _verbaleService.TotPuntiDecurtati();
            return View(verbali);
        }

        public IActionResult TotImporti ()
        {
            List<VerbaleViewModel> verbali = _verbaleService.VisualizzazionePiuDiDieciPunti();
            return View(verbali);
        }

        public IActionResult QuattroCentoEuro ()
        {
            List<VerbaleViewModel> verbali = _verbaleService.VisualizzazionePiuDiQuattroCentoEuro();
            return View(verbali);
        }

        public IActionResult Menu ()
        {
            
            return View();
        }
    }
}

progetto Venederdi 19 07/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="it">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Home Page - Ufficio Carabinieri</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
    <link rel="stylesheet" href="./css/Home.css">

</head>
<body>
    <!-- Barra di navigazione -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <a class="navbar-brand" href="#">Ufficio Carabinieri</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNav">
          
        </div>
    </nav>

    <!-- Jumbotron con messaggio di benvenuto -->
    <div class="jumbotron">
        <div class="container">
            <h1 class="display-4">Benvenuto all'Ufficio Carabinieri</h1>
            <p class="lead">Gestione delle anagrafiche, multe e verbali</p>
            <hr class="my-4">
            <p>Questa è la nostra home page dove puoi trovare informazioni e accedere ai nostri servizi.</p>
        </div>
    </div>

    <!-- Sezione contenente le informazioni principali -->
    <div class="container">
        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body text-center">
                        
                        <img src="https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6bfbIOjoGyFurQpXIonG2YIf29KafPpdt8MO-efDQ_BW_G2uU57_LK9fAavnI_c6f83M&usqp=CAU" alt="Anagrafe" class="card-img-top">
                        
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body text-center">
                        
                        <img src="https://exforma.net/wp-content/uploads/arruolarsi-nei-carabinieri.jpg" alt="Multe" class="card-img-top">
                        
                    </div>
                </div>
            </div>
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body text-center">
                       
                        <img src="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEh_maBRajSHd6GATFB7vPJQoCjbx6F4HTKAfQSkMPGBfgdcdGJpNWn7PQ_kO4l88b-uRsqajvAJMyspz01UOq2kv1ZbwzUnCNQpeb0r5s6at8M6_o2z_PvJLv8QvvuJ6EQgHzGkM1_36sk/s1600/IMG_5949+-+Copia.JPG" alt="Verbali" class="card-img-top">
                        
                    </div>
                </div>
            </div>
        </div>
    </div>


    <!-- Script JavaScript -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

progetto Venederdi 19 07/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - progetto_Venederdi_19_07</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/progetto_Venederdi_19_07.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">progetto_Venederdi_19_07</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Utenti" asp-action="Index">Utenti</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verbale" asp-action="Index">Verbali</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verbale" asp-action="Menu">Back Office</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - progetto_Venederdi_19_07 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

progetto Venederdi 19 07/Views/Utenti/Index.cshtml
@model IEnumerable<progetto_Venederdi_19_07.ViewModels.UtentiViewModel>

@{
    ViewData["Title"] = "Index";
}

<link href="~/css/Utenti.css" rel="stylesheet" />


<h1>Utenti</h1>

<p>
    <a asp-action="NuovoUtente" id="crea">Crea Utente</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.IdAnagrafica)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cod_Fisc)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Indirizzo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Città)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cap)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.IdAnagrafica)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cognome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cod_Fisc)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Indirizzo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Città)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cap)
            </td>
           
        </tr>
}
    </tbody>
</table>

progetto Venederdi 19 07/Views/Utenti/NuovoUtente.cshtml
@model progetto_Venederdi_19_07.Anagrafica

@{
    ViewData["Title"] = "NuovoUtente";
}

<h1>NuovoUtente</h1>

<h4>Anagrafica</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NuovoUtente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdAnagrafica" class="control-label"></label>
                <input asp-for="IdAnagrafica" class="form-control" />
                <span asp-validation-for="IdAnagrafica" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cognome" class="control-label"></label>
                <input asp-for="Cognome" class="form-control" />
                <span asp-validation-for="Cognome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cod_Fisc" class="control-label"></label>
                <input asp-for="Cod_Fisc" class="form-control" />
                <span asp-validation-for="Cod_Fisc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Indirizzo" class="control-label"></label>
                <input asp-for="Indirizzo" class="form-control" />
                <span asp-validation-for="Indirizzo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Città" class="control-label"></label>
                <input asp-for="Città" class="form-control" />
                <span asp-validation-for="Città" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cap" class="control-label"></label>
                <input asp-for="Cap" class="form-control" />
                <span asp-validation-for="Cap" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

progetto Venederdi 19 07/Views/Verbale/Index.cshtml
@model List<progetto_Venederdi_19_07.ViewModels.VerbaleViewModel>

@{
    ViewBag.Title = "Elenco Verbali";
}

<link href="~/css/Verbali.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<p>
    <a asp-action="NuovoVerbale" id="crea">Crea Verbale</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>Nome</th>
            <th>Cognome</th>
            <th>Descrizione</th>
            <th>Totale Verbali</th>
            <th>ID Verbale</th>
            <th>ID Utente</th>
            <th>ID Violazione</th>
            <th>Data Violazione</th>
            <th>Indirizzo Violazione</th>
            <th>Nominativo Agente</th>
            <th>Data Trascrizione Verbale</th>
            <th>Importo</th>
            <th>Decurtamento Punti</th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.Nome</td>
            <td>@item.Cognome</td>
            <td>@item.Descrizione</td>
            <td>@item.TotVerbali</td>
            <td>@item.IdVerbale</td>
            <td>@item.IdUtente</td>
            <td>@item.IdViolazione</td>
            <td>@item.DataViolazione.ToString("dd/MM/yyyy")</td>
            <td>@item.IndirizzoViolazione</td>
            <td>@item.Nominativo_Agente</td>
            <td>@item.DataTrascrizioneVerbale</td>
            <td>@item.Importo.ToString("C")</td>
            <td>@item.DecurtamentoPunti</td>
        </tr>
    }
    </tbody>
</table>

progetto Venederdi 19 07/Views/Verbale/Menu.cshtml
@{
    ViewData["Title"] = "Menu";
}

<link href="~/css/Menu.css" rel="stylesheet" />

<div class="container back-office-container">
    <div class="row">
        <div class="col-md-6 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Totale Verbali</h5>
                    <p class="card-text">Visualizza il totale dei verbali trascritti.</p>
                    <a asp-action="TotVerbali" class="btn btn-primary btn-custom">Vai a Totale Verbali</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Totale Punti</h5>
                    <p class="card-text">Visualizza il totale dei punti decurtati.</p>
                    <a asp-action="TotPunti" class="btn btn-primary btn-custom">Vai a Totale Punti</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Totale Importi</h5>
                    <p class="card-text">Visualizza il totale degli importi delle multe.</p>
                    <a asp-action="TotImporti" class="btn btn-primary btn-custom">Vai a Totale Importi</a>
                </div>
            </div>
        </div>
        <div class="col-md-6 mb-4">
            <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Totale Maggiore di 400$</h5>
                    <p class="card-text">Visualizza il totale delle multe superiori a 400$.</p>
                    <a asp-action="QuattroCentoEuro" class="btn btn-primary btn-custom">Vai a Totale Maggiore di 400$</a>
                </div>
            </div>
        </div>
    </div>
</div>

progetto Venederdi 19 07/Views/Verbale/NuovoVerbale.cshtml
@model progetto_Venederdi_19_07.Verbale

@{
    ViewData["Title"] = "NuovoVerbale";
}


<h1>NuovoVerbale</h1>

<h4>Verbale</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="NuovoVerbale">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="IdUtente" class="control-label"></label>
                <select asp-for="IdUtente" class="form-select">
                    <option value="">Seleziona un utente</option>
                    @foreach (var item in ViewBag.Utenti)
                    {
                        <option value="@item.IdAnagrafica">@item.Cognome</option>
                    }
                </select>
                <span asp-validation-for="IdUtente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdViolazione" class="control-label"></label>
                <select asp-for="IdViolazione" class="form-select">
                    <option value="">Seleziona una violazione</option>
                    @foreach (var item in ViewBag.Violazioni)
                    {
                        <option value="@item.IdViolazione">@item.Descrizione</option>
                    }
                </select>
                <span asp-validation-for="IdViolazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataViolazione" class="control-label"></label>
                <input asp-for="DataViolazione" class="form-control" />
                <span asp-validation-for="DataViolazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IndirizzoViolazione" class="control-label"></label>
                <input asp-for="IndirizzoViolazione" class="form-control" />
                <span asp-validation-for="IndirizzoViolazione" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Nominativo_Agente" class="control-label"></label>
                <input asp-for="Nominativo_Agente" class="form-control" />
                <span asp-validation-for="Nominativo_Agente" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataTrascrizioneVerbale" class="control-label"></label>
                <input asp-for="DataTrascrizioneVerbale" class="form-control" />
                <span asp-validation-for="DataTrascrizioneVerbale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Importo" class="control-label"></label>
                <input asp-for="Importo" class="form-control" />
                <span asp-validation-for="Importo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DecurtamentoPunti" class="control-label"></label>
                <input asp-for="DecurtamentoPunti" class="form-control" />
                <span asp-validation-for="DecurtamentoPunti" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

progetto Venederdi 19 07/Views/Verbale/QuattroCentoEuro.cshtml
@model IEnumerable<progetto_Venederdi_19_07.ViewModels.VerbaleViewModel>

@{
    ViewData["Title"] = "TotPunti";
}

<h1>TotPunti</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataViolazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DecurtamentoPunti)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Descrizione)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cognome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataViolazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DecurtamentoPunti)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Importo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Descrizione)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>

progetto Venederdi 19 07/Views/Verbale/TotImporti.cshtml
@model IEnumerable<progetto_Venederdi_19_07.ViewModels.VerbaleViewModel>

@{
    ViewData["Title"] = "TotImporti";
}

<h1>TotImporti</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
           
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cognome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Importo)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataViolazione)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DecurtamentoPunti)
            </th>


            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                
                <td>
                    @Html.DisplayFor(modelItem => item.Nome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Cognome)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Importo)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DataViolazione)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DecurtamentoPunti)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ }) |
                    @Html.ActionLink("Delete", "Delete", new { /* id=item.PrimaryKey */ })
                </td>
            </tr>
        }
    </tbody>
</table>